name: ruracare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.4.1
  riverpod: ^2.4.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  share_plus: ^7.0.1
  url_launcher: ^6.1.11
  intl: ^0.19.0
  riverpod_annotation: ^2.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.1
  flutter_secure_storage: ^9.2.4
  convex_bottom_bar: ^3.2.0
  google_fonts: ^6.1.0
  clipboard: ^0.1.3
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/active_2.jpg
    - assets/faicon.png
    - assets/dashboard.png
    - assets/teams.png
    - assets/wallet.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/faicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
    
