name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests if they exist
        run: |
          if [ -d "test" ]; then
            flutter test
          else
            echo "No tests found, skipping test step"
          fi

      - name: Analyze project
        run: flutter analyze

      - name: Build Android AppBundle
        run: |
          flutter build appbundle --release
          ls -la build/app/outputs/bundle/release/

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error
          retention-days: 7

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests if they exist
        run: |
          if [ -d "test" ]; then
            flutter test
          else
            echo "No tests found, skipping test step"
          fi

      - name: Build iOS
        run: |
          flutter build ipa --release --no-codesign
          ls -la build/ios/ipa/

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/ipa/*.ipa
          if-no-files-found: error
          retention-days: 7
